spring:
  application:
    name: Red Coconut

  # Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10GB}
      max-request-size: ${MAX_REQUEST_SIZE:10GB}
      resolve-lazily: true

red-coconut:
  storage:
    # Location: a bucket name for cloud storage or directory path for local storage
    location: ${STORAGE_LOCATION:tmp}
    # Whether to use chunked uploads for large files
    use-chunked-uploads: ${STORAGE_USE_CHUNKED:true}
    # Size threshold for chunked uploads (default: 100MB)
    chunk-threshold: ${STORAGE_CHUNK_THRESHOLD:104857600}
    # Size of each chunk (default: 10MB)
    chunk-size: ${STORAGE_CHUNK_SIZE:10485760}
