app:
  cognito:
    client-id: "${AWS_COGNITO_CLIENT_ID}"
    logout-uri: "${AWS_COGNITO_LOGOUT_URI}"
    logout-redirect-uri: "http://localhost:8080/login"

spring:
  application:
    name: Red Coconut

  cloud:
    aws:
      region:
        static: "${AWS_REGION}"
      credentials:
        access-key: "${AWS_ACCESS_KEY_ID}"
        secret-key: "${AWS_SECRET_ACCESS_KEY}"

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: "${AWS_COGNITO_CLIENT_ID}"
            client-secret: "${AWS_COGNITO_CLIENT_SECRET}"
            scope:
              - phone
              - openid
              - email
        provider:
          cognito:
            issuer-uri: "${AWS_COGNITO_ISSUER_URI}"

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    url: ${POSTGRES_DB_HOST}/red_coconut
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false

  data:
    rest:
      base-path: /api
      default-page-size: 25
      max-page-size: 100
      return-body-on-create: true
      return-body-on-update: true

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE
    io:
      awspring:
        cloud: TRACE
