@JSESSIONID=8F4801D85436575A0EFDCDE80613718C

### List Clients
GET http://localhost:8080/api/clients
Cookie: JSESSIONID={{JSESSIONID}}

### List Clients with Pagination
GET http://localhost:8080/api/clients?page=1&size=2&sort=id,asc
Cookie: JSESSIONID={{JSESSIONID}}

### Get Client by ID
GET http://localhost:8080/api/clients/1
Cookie: JSESSIONID={{JSESSIONID}}

### Create Client
POST http://localhost:8080/api/clients
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

{
  "username": "johncena",
  "firstName": "John",
  "lastName": "Cena"
}

### Update Client (Replace)
PUT http://localhost:8080/api/clients/3
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

{
  "username": "jimdoe",
  "firstName": "James",
  "lastName": "Doe"
}

### Update Client (Patch)
PATCH http://localhost:8080/api/clients/4
Content-Type: application/json
Cookie: JSESSIONID={{JSESSIONID}}

{
  "username": "johndoe"
}

### Delete Client
DELETE http://localhost:8080/api/clients/1
Cookie: JSESSIONID={{JSESSIONID}}


### Find Client by username
@username=jimdoe
GET http://localhost:8080/api/clients/search/findByUsername?username={{username}}
Cookie: JSESSIONID={{JSESSIONID}}
